title:              MyDataJourney # Data Science Concepts
email:              dorber3@gmail.com
description:        A blog to review data science concept
author:             Dor Bernsohn
baseurl:            ""
url:                "https://dorbernsohn.github.io"

# Social Profiles
twitter_username:
facebook_username:
instagram_username:
github_username:    DorBernsohn
linkedin_username:  dor-bernsohn-70b2b1146
goodreads_username: 150080273-dor-bernsohn

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
higlighter: rouge
# theme: jekyll-theme-clean-blog
remote_theme: hydecorp/hydejack